version: '3.9'

services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:15.3-alpine3.18
    ports:
      - ${PGSQL_PORT}:${PGSQL_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB_NAME}
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

  account:
    container_name: ${APP_NAME}-account-service
    image: ${APP_NAME}-account
    restart: always
    ports:
      - ${ACCOUNT_SERVICE_HTTP_PORT}:${ACCOUNT_SERVICE_HTTP_PORT}
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./services/account:/app/services/account
    environment:
      # app
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      # account-service
      HTTP_PORT: ${ACCOUNT_SERVICE_HTTP_PORT}
      # pgsql
      PGSQL_USERNAME: ${PGSQL_USERNAME}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
      PGSQL_HOST: ${PGSQL_HOST}
      PGSQL_PORT: ${PGSQL_PORT}
      PGSQL_DB_NAME: ${PGSQL_DB_NAME}
      PGSQL_QUERY_PARAMS: ${PGSQL_QUERY_PARAMS}