version: "3"

dotenv: [ '.env' ]

includes:
  go:
    taskfile: ./taskfiles/golang.yml
    vars:
      PACKAGES:
        sh: go list ./...
  docker:
    taskfile: ./taskfiles/docker.yml
  mock:
    taskfile: ./taskfiles/mock.yml
  migrate:
    taskfile: ./taskfiles/migrate.yml
    vars:
      PGSQL_DSN: postgres://{{.PGSQL_USERNAME}}:{{.PGSQL_PASSWORD}}@localhost:{{.PGSQL_PORT}}/{{.PGSQL_DB_NAME}}?{{.PGSQL_QUERY_PARAMS}}

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - go install github.com/google/wire/cmd/wire@latest
      - brew install golangci-lint
      - brew install golang-migrate
      - go install github.com/cosmtrek/air@latest
      - go install go.uber.org/mock/mockgen@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - brew install pre-commit
      - pre-commit install

  build:images:
    desc: Build images for all services.
    cmds:
      - echo 'Building account-service image...'
      - task docker:build BIN=account PORT={{.ACCOUNT_SERVICE_HTTP_PORT}}

  audit:
    desc: Audits Go codes. (Shorthand for `task go:audit`)
    cmds:
      - task: go:audit

  swag:
    desc: Generate swagger documentation.
    cmds:
      - echo 'Generating account-service swagger documentation...'
      - swag init -g ./services/account/main.go -o ./services/account/docs

  wire:
    desc: Wire up dependencies for all services.
    cmds:
      - echo 'Wiring up the account-service...'
      - cd ./services/account/application && wire

  run:
    desc: Run the application in docker container.
    deps:
      - build:images
      - swag
      - wire
    cmds:
      - echo 'Running the application...'
      - task: docker:compose:up