version: "3"

dotenv: [ '.env' ]

includes:
  go:
    taskfile: ./taskfiles/golang.yml
    vars:
      PACKAGES:
        sh: go list ./...
  docker:
    taskfile: ./taskfiles/docker.yml

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - brew install golangci-lint
      - go install github.com/cosmtrek/air@latest

  build:images:
    desc: Build images for all services.
    cmds:
      - task docker:build BIN=account PORT={{.ACCOUNT_SERVICE_PORT}}

  run:
    desc: Run the application in docker container.
    deps:
      - build:images
    cmds:
      - echo 'Running the application...'
      - task: docker:compose:up

  audit:
    desc: Audits Go codes. (Shorthand for `task go:audit`)
    cmds:
      - task: go:audit