# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up golang
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./...